//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace OneTo50.OneTo50ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OneTo50ServiceReference.OneTo50Soap")]
    public interface OneTo50Soap {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.IAsyncResult BeginHelloWorld(OneTo50.OneTo50ServiceReference.HelloWorldRequest request, System.AsyncCallback callback, object asyncState);
        
        OneTo50.OneTo50ServiceReference.HelloWorldResponse EndHelloWorld(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/UpdateScore", ReplyAction="*")]
        System.IAsyncResult BeginUpdateScore(OneTo50.OneTo50ServiceReference.UpdateScoreRequest request, System.AsyncCallback callback, object asyncState);
        
        OneTo50.OneTo50ServiceReference.UpdateScoreResponse EndUpdateScore(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/GetRecordsByPage", ReplyAction="*")]
        System.IAsyncResult BeginGetRecordsByPage(OneTo50.OneTo50ServiceReference.GetRecordsByPageRequest request, System.AsyncCallback callback, object asyncState);
        
        OneTo50.OneTo50ServiceReference.GetRecordsByPageResponse EndGetRecordsByPage(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/GetTodayRecordsByPage", ReplyAction="*")]
        System.IAsyncResult BeginGetTodayRecordsByPage(OneTo50.OneTo50ServiceReference.GetTodayRecordsByPageRequest request, System.AsyncCallback callback, object asyncState);
        
        OneTo50.OneTo50ServiceReference.GetTodayRecordsByPageResponse EndGetTodayRecordsByPage(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/GetCountryScore", ReplyAction="*")]
        System.IAsyncResult BeginGetCountryScore(OneTo50.OneTo50ServiceReference.GetCountryScoreRequest request, System.AsyncCallback callback, object asyncState);
        
        OneTo50.OneTo50ServiceReference.GetCountryScoreResponse EndGetCountryScore(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public OneTo50.OneTo50ServiceReference.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(OneTo50.OneTo50ServiceReference.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public OneTo50.OneTo50ServiceReference.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(OneTo50.OneTo50ServiceReference.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateScoreRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateScore", Namespace="http://tempuri.org/", Order=0)]
        public OneTo50.OneTo50ServiceReference.UpdateScoreRequestBody Body;
        
        public UpdateScoreRequest() {
        }
        
        public UpdateScoreRequest(OneTo50.OneTo50ServiceReference.UpdateScoreRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateScoreRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double score;
        
        public UpdateScoreRequestBody() {
        }
        
        public UpdateScoreRequestBody(string userName, double score) {
            this.userName = userName;
            this.score = score;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateScoreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateScoreResponse", Namespace="http://tempuri.org/", Order=0)]
        public OneTo50.OneTo50ServiceReference.UpdateScoreResponseBody Body;
        
        public UpdateScoreResponse() {
        }
        
        public UpdateScoreResponse(OneTo50.OneTo50ServiceReference.UpdateScoreResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateScoreResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdateScoreResult;
        
        public UpdateScoreResponseBody() {
        }
        
        public UpdateScoreResponseBody(bool UpdateScoreResult) {
            this.UpdateScoreResult = UpdateScoreResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRecordsByPageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRecordsByPage", Namespace="http://tempuri.org/", Order=0)]
        public OneTo50.OneTo50ServiceReference.GetRecordsByPageRequestBody Body;
        
        public GetRecordsByPageRequest() {
        }
        
        public GetRecordsByPageRequest(OneTo50.OneTo50ServiceReference.GetRecordsByPageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRecordsByPageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int pageSize;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int pageIndex;
        
        public GetRecordsByPageRequestBody() {
        }
        
        public GetRecordsByPageRequestBody(int pageSize, int pageIndex) {
            this.pageSize = pageSize;
            this.pageIndex = pageIndex;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRecordsByPageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRecordsByPageResponse", Namespace="http://tempuri.org/", Order=0)]
        public OneTo50.OneTo50ServiceReference.GetRecordsByPageResponseBody Body;
        
        public GetRecordsByPageResponse() {
        }
        
        public GetRecordsByPageResponse(OneTo50.OneTo50ServiceReference.GetRecordsByPageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRecordsByPageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetRecordsByPageResult;
        
        public GetRecordsByPageResponseBody() {
        }
        
        public GetRecordsByPageResponseBody(string GetRecordsByPageResult) {
            this.GetRecordsByPageResult = GetRecordsByPageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTodayRecordsByPageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTodayRecordsByPage", Namespace="http://tempuri.org/", Order=0)]
        public OneTo50.OneTo50ServiceReference.GetTodayRecordsByPageRequestBody Body;
        
        public GetTodayRecordsByPageRequest() {
        }
        
        public GetTodayRecordsByPageRequest(OneTo50.OneTo50ServiceReference.GetTodayRecordsByPageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTodayRecordsByPageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int pageSize;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int pageIndex;
        
        public GetTodayRecordsByPageRequestBody() {
        }
        
        public GetTodayRecordsByPageRequestBody(int pageSize, int pageIndex) {
            this.pageSize = pageSize;
            this.pageIndex = pageIndex;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTodayRecordsByPageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTodayRecordsByPageResponse", Namespace="http://tempuri.org/", Order=0)]
        public OneTo50.OneTo50ServiceReference.GetTodayRecordsByPageResponseBody Body;
        
        public GetTodayRecordsByPageResponse() {
        }
        
        public GetTodayRecordsByPageResponse(OneTo50.OneTo50ServiceReference.GetTodayRecordsByPageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTodayRecordsByPageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetTodayRecordsByPageResult;
        
        public GetTodayRecordsByPageResponseBody() {
        }
        
        public GetTodayRecordsByPageResponseBody(string GetTodayRecordsByPageResult) {
            this.GetTodayRecordsByPageResult = GetTodayRecordsByPageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCountryScoreRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCountryScore", Namespace="http://tempuri.org/", Order=0)]
        public OneTo50.OneTo50ServiceReference.GetCountryScoreRequestBody Body;
        
        public GetCountryScoreRequest() {
        }
        
        public GetCountryScoreRequest(OneTo50.OneTo50ServiceReference.GetCountryScoreRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetCountryScoreRequestBody {
        
        public GetCountryScoreRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCountryScoreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCountryScoreResponse", Namespace="http://tempuri.org/", Order=0)]
        public OneTo50.OneTo50ServiceReference.GetCountryScoreResponseBody Body;
        
        public GetCountryScoreResponse() {
        }
        
        public GetCountryScoreResponse(OneTo50.OneTo50ServiceReference.GetCountryScoreResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCountryScoreResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetCountryScoreResult;
        
        public GetCountryScoreResponseBody() {
        }
        
        public GetCountryScoreResponseBody(string GetCountryScoreResult) {
            this.GetCountryScoreResult = GetCountryScoreResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OneTo50SoapChannel : OneTo50.OneTo50ServiceReference.OneTo50Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UpdateScoreCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public UpdateScoreCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetRecordsByPageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetRecordsByPageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetTodayRecordsByPageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetTodayRecordsByPageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetCountryScoreCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetCountryScoreCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OneTo50SoapClient : System.ServiceModel.ClientBase<OneTo50.OneTo50ServiceReference.OneTo50Soap>, OneTo50.OneTo50ServiceReference.OneTo50Soap {
        
        private BeginOperationDelegate onBeginHelloWorldDelegate;
        
        private EndOperationDelegate onEndHelloWorldDelegate;
        
        private System.Threading.SendOrPostCallback onHelloWorldCompletedDelegate;
        
        private BeginOperationDelegate onBeginUpdateScoreDelegate;
        
        private EndOperationDelegate onEndUpdateScoreDelegate;
        
        private System.Threading.SendOrPostCallback onUpdateScoreCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetRecordsByPageDelegate;
        
        private EndOperationDelegate onEndGetRecordsByPageDelegate;
        
        private System.Threading.SendOrPostCallback onGetRecordsByPageCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetTodayRecordsByPageDelegate;
        
        private EndOperationDelegate onEndGetTodayRecordsByPageDelegate;
        
        private System.Threading.SendOrPostCallback onGetTodayRecordsByPageCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetCountryScoreDelegate;
        
        private EndOperationDelegate onEndGetCountryScoreDelegate;
        
        private System.Threading.SendOrPostCallback onGetCountryScoreCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public OneTo50SoapClient() {
        }
        
        public OneTo50SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OneTo50SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OneTo50SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OneTo50SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<HelloWorldCompletedEventArgs> HelloWorldCompleted;
        
        public event System.EventHandler<UpdateScoreCompletedEventArgs> UpdateScoreCompleted;
        
        public event System.EventHandler<GetRecordsByPageCompletedEventArgs> GetRecordsByPageCompleted;
        
        public event System.EventHandler<GetTodayRecordsByPageCompletedEventArgs> GetTodayRecordsByPageCompleted;
        
        public event System.EventHandler<GetCountryScoreCompletedEventArgs> GetCountryScoreCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult OneTo50.OneTo50ServiceReference.OneTo50Soap.BeginHelloWorld(OneTo50.OneTo50ServiceReference.HelloWorldRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginHelloWorld(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginHelloWorld(System.AsyncCallback callback, object asyncState) {
            OneTo50.OneTo50ServiceReference.HelloWorldRequest inValue = new OneTo50.OneTo50ServiceReference.HelloWorldRequest();
            inValue.Body = new OneTo50.OneTo50ServiceReference.HelloWorldRequestBody();
            return ((OneTo50.OneTo50ServiceReference.OneTo50Soap)(this)).BeginHelloWorld(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OneTo50.OneTo50ServiceReference.HelloWorldResponse OneTo50.OneTo50ServiceReference.OneTo50Soap.EndHelloWorld(System.IAsyncResult result) {
            return base.Channel.EndHelloWorld(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndHelloWorld(System.IAsyncResult result) {
            OneTo50.OneTo50ServiceReference.HelloWorldResponse retVal = ((OneTo50.OneTo50ServiceReference.OneTo50Soap)(this)).EndHelloWorld(result);
            return retVal.Body.HelloWorldResult;
        }
        
        private System.IAsyncResult OnBeginHelloWorld(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginHelloWorld(callback, asyncState);
        }
        
        private object[] OnEndHelloWorld(System.IAsyncResult result) {
            string retVal = this.EndHelloWorld(result);
            return new object[] {
                    retVal};
        }
        
        private void OnHelloWorldCompleted(object state) {
            if ((this.HelloWorldCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        public void HelloWorldAsync(object userState) {
            if ((this.onBeginHelloWorldDelegate == null)) {
                this.onBeginHelloWorldDelegate = new BeginOperationDelegate(this.OnBeginHelloWorld);
            }
            if ((this.onEndHelloWorldDelegate == null)) {
                this.onEndHelloWorldDelegate = new EndOperationDelegate(this.OnEndHelloWorld);
            }
            if ((this.onHelloWorldCompletedDelegate == null)) {
                this.onHelloWorldCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnHelloWorldCompleted);
            }
            base.InvokeAsync(this.onBeginHelloWorldDelegate, null, this.onEndHelloWorldDelegate, this.onHelloWorldCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult OneTo50.OneTo50ServiceReference.OneTo50Soap.BeginUpdateScore(OneTo50.OneTo50ServiceReference.UpdateScoreRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginUpdateScore(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginUpdateScore(string userName, double score, System.AsyncCallback callback, object asyncState) {
            OneTo50.OneTo50ServiceReference.UpdateScoreRequest inValue = new OneTo50.OneTo50ServiceReference.UpdateScoreRequest();
            inValue.Body = new OneTo50.OneTo50ServiceReference.UpdateScoreRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.score = score;
            return ((OneTo50.OneTo50ServiceReference.OneTo50Soap)(this)).BeginUpdateScore(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OneTo50.OneTo50ServiceReference.UpdateScoreResponse OneTo50.OneTo50ServiceReference.OneTo50Soap.EndUpdateScore(System.IAsyncResult result) {
            return base.Channel.EndUpdateScore(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool EndUpdateScore(System.IAsyncResult result) {
            OneTo50.OneTo50ServiceReference.UpdateScoreResponse retVal = ((OneTo50.OneTo50ServiceReference.OneTo50Soap)(this)).EndUpdateScore(result);
            return retVal.Body.UpdateScoreResult;
        }
        
        private System.IAsyncResult OnBeginUpdateScore(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string userName = ((string)(inValues[0]));
            double score = ((double)(inValues[1]));
            return this.BeginUpdateScore(userName, score, callback, asyncState);
        }
        
        private object[] OnEndUpdateScore(System.IAsyncResult result) {
            bool retVal = this.EndUpdateScore(result);
            return new object[] {
                    retVal};
        }
        
        private void OnUpdateScoreCompleted(object state) {
            if ((this.UpdateScoreCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.UpdateScoreCompleted(this, new UpdateScoreCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void UpdateScoreAsync(string userName, double score) {
            this.UpdateScoreAsync(userName, score, null);
        }
        
        public void UpdateScoreAsync(string userName, double score, object userState) {
            if ((this.onBeginUpdateScoreDelegate == null)) {
                this.onBeginUpdateScoreDelegate = new BeginOperationDelegate(this.OnBeginUpdateScore);
            }
            if ((this.onEndUpdateScoreDelegate == null)) {
                this.onEndUpdateScoreDelegate = new EndOperationDelegate(this.OnEndUpdateScore);
            }
            if ((this.onUpdateScoreCompletedDelegate == null)) {
                this.onUpdateScoreCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnUpdateScoreCompleted);
            }
            base.InvokeAsync(this.onBeginUpdateScoreDelegate, new object[] {
                        userName,
                        score}, this.onEndUpdateScoreDelegate, this.onUpdateScoreCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult OneTo50.OneTo50ServiceReference.OneTo50Soap.BeginGetRecordsByPage(OneTo50.OneTo50ServiceReference.GetRecordsByPageRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetRecordsByPage(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetRecordsByPage(int pageSize, int pageIndex, System.AsyncCallback callback, object asyncState) {
            OneTo50.OneTo50ServiceReference.GetRecordsByPageRequest inValue = new OneTo50.OneTo50ServiceReference.GetRecordsByPageRequest();
            inValue.Body = new OneTo50.OneTo50ServiceReference.GetRecordsByPageRequestBody();
            inValue.Body.pageSize = pageSize;
            inValue.Body.pageIndex = pageIndex;
            return ((OneTo50.OneTo50ServiceReference.OneTo50Soap)(this)).BeginGetRecordsByPage(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OneTo50.OneTo50ServiceReference.GetRecordsByPageResponse OneTo50.OneTo50ServiceReference.OneTo50Soap.EndGetRecordsByPage(System.IAsyncResult result) {
            return base.Channel.EndGetRecordsByPage(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndGetRecordsByPage(System.IAsyncResult result) {
            OneTo50.OneTo50ServiceReference.GetRecordsByPageResponse retVal = ((OneTo50.OneTo50ServiceReference.OneTo50Soap)(this)).EndGetRecordsByPage(result);
            return retVal.Body.GetRecordsByPageResult;
        }
        
        private System.IAsyncResult OnBeginGetRecordsByPage(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int pageSize = ((int)(inValues[0]));
            int pageIndex = ((int)(inValues[1]));
            return this.BeginGetRecordsByPage(pageSize, pageIndex, callback, asyncState);
        }
        
        private object[] OnEndGetRecordsByPage(System.IAsyncResult result) {
            string retVal = this.EndGetRecordsByPage(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetRecordsByPageCompleted(object state) {
            if ((this.GetRecordsByPageCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetRecordsByPageCompleted(this, new GetRecordsByPageCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetRecordsByPageAsync(int pageSize, int pageIndex) {
            this.GetRecordsByPageAsync(pageSize, pageIndex, null);
        }
        
        public void GetRecordsByPageAsync(int pageSize, int pageIndex, object userState) {
            if ((this.onBeginGetRecordsByPageDelegate == null)) {
                this.onBeginGetRecordsByPageDelegate = new BeginOperationDelegate(this.OnBeginGetRecordsByPage);
            }
            if ((this.onEndGetRecordsByPageDelegate == null)) {
                this.onEndGetRecordsByPageDelegate = new EndOperationDelegate(this.OnEndGetRecordsByPage);
            }
            if ((this.onGetRecordsByPageCompletedDelegate == null)) {
                this.onGetRecordsByPageCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetRecordsByPageCompleted);
            }
            base.InvokeAsync(this.onBeginGetRecordsByPageDelegate, new object[] {
                        pageSize,
                        pageIndex}, this.onEndGetRecordsByPageDelegate, this.onGetRecordsByPageCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult OneTo50.OneTo50ServiceReference.OneTo50Soap.BeginGetTodayRecordsByPage(OneTo50.OneTo50ServiceReference.GetTodayRecordsByPageRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetTodayRecordsByPage(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetTodayRecordsByPage(int pageSize, int pageIndex, System.AsyncCallback callback, object asyncState) {
            OneTo50.OneTo50ServiceReference.GetTodayRecordsByPageRequest inValue = new OneTo50.OneTo50ServiceReference.GetTodayRecordsByPageRequest();
            inValue.Body = new OneTo50.OneTo50ServiceReference.GetTodayRecordsByPageRequestBody();
            inValue.Body.pageSize = pageSize;
            inValue.Body.pageIndex = pageIndex;
            return ((OneTo50.OneTo50ServiceReference.OneTo50Soap)(this)).BeginGetTodayRecordsByPage(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OneTo50.OneTo50ServiceReference.GetTodayRecordsByPageResponse OneTo50.OneTo50ServiceReference.OneTo50Soap.EndGetTodayRecordsByPage(System.IAsyncResult result) {
            return base.Channel.EndGetTodayRecordsByPage(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndGetTodayRecordsByPage(System.IAsyncResult result) {
            OneTo50.OneTo50ServiceReference.GetTodayRecordsByPageResponse retVal = ((OneTo50.OneTo50ServiceReference.OneTo50Soap)(this)).EndGetTodayRecordsByPage(result);
            return retVal.Body.GetTodayRecordsByPageResult;
        }
        
        private System.IAsyncResult OnBeginGetTodayRecordsByPage(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int pageSize = ((int)(inValues[0]));
            int pageIndex = ((int)(inValues[1]));
            return this.BeginGetTodayRecordsByPage(pageSize, pageIndex, callback, asyncState);
        }
        
        private object[] OnEndGetTodayRecordsByPage(System.IAsyncResult result) {
            string retVal = this.EndGetTodayRecordsByPage(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetTodayRecordsByPageCompleted(object state) {
            if ((this.GetTodayRecordsByPageCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetTodayRecordsByPageCompleted(this, new GetTodayRecordsByPageCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetTodayRecordsByPageAsync(int pageSize, int pageIndex) {
            this.GetTodayRecordsByPageAsync(pageSize, pageIndex, null);
        }
        
        public void GetTodayRecordsByPageAsync(int pageSize, int pageIndex, object userState) {
            if ((this.onBeginGetTodayRecordsByPageDelegate == null)) {
                this.onBeginGetTodayRecordsByPageDelegate = new BeginOperationDelegate(this.OnBeginGetTodayRecordsByPage);
            }
            if ((this.onEndGetTodayRecordsByPageDelegate == null)) {
                this.onEndGetTodayRecordsByPageDelegate = new EndOperationDelegate(this.OnEndGetTodayRecordsByPage);
            }
            if ((this.onGetTodayRecordsByPageCompletedDelegate == null)) {
                this.onGetTodayRecordsByPageCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetTodayRecordsByPageCompleted);
            }
            base.InvokeAsync(this.onBeginGetTodayRecordsByPageDelegate, new object[] {
                        pageSize,
                        pageIndex}, this.onEndGetTodayRecordsByPageDelegate, this.onGetTodayRecordsByPageCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult OneTo50.OneTo50ServiceReference.OneTo50Soap.BeginGetCountryScore(OneTo50.OneTo50ServiceReference.GetCountryScoreRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetCountryScore(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetCountryScore(System.AsyncCallback callback, object asyncState) {
            OneTo50.OneTo50ServiceReference.GetCountryScoreRequest inValue = new OneTo50.OneTo50ServiceReference.GetCountryScoreRequest();
            inValue.Body = new OneTo50.OneTo50ServiceReference.GetCountryScoreRequestBody();
            return ((OneTo50.OneTo50ServiceReference.OneTo50Soap)(this)).BeginGetCountryScore(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OneTo50.OneTo50ServiceReference.GetCountryScoreResponse OneTo50.OneTo50ServiceReference.OneTo50Soap.EndGetCountryScore(System.IAsyncResult result) {
            return base.Channel.EndGetCountryScore(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndGetCountryScore(System.IAsyncResult result) {
            OneTo50.OneTo50ServiceReference.GetCountryScoreResponse retVal = ((OneTo50.OneTo50ServiceReference.OneTo50Soap)(this)).EndGetCountryScore(result);
            return retVal.Body.GetCountryScoreResult;
        }
        
        private System.IAsyncResult OnBeginGetCountryScore(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetCountryScore(callback, asyncState);
        }
        
        private object[] OnEndGetCountryScore(System.IAsyncResult result) {
            string retVal = this.EndGetCountryScore(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetCountryScoreCompleted(object state) {
            if ((this.GetCountryScoreCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetCountryScoreCompleted(this, new GetCountryScoreCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetCountryScoreAsync() {
            this.GetCountryScoreAsync(null);
        }
        
        public void GetCountryScoreAsync(object userState) {
            if ((this.onBeginGetCountryScoreDelegate == null)) {
                this.onBeginGetCountryScoreDelegate = new BeginOperationDelegate(this.OnBeginGetCountryScore);
            }
            if ((this.onEndGetCountryScoreDelegate == null)) {
                this.onEndGetCountryScoreDelegate = new EndOperationDelegate(this.OnEndGetCountryScore);
            }
            if ((this.onGetCountryScoreCompletedDelegate == null)) {
                this.onGetCountryScoreCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetCountryScoreCompleted);
            }
            base.InvokeAsync(this.onBeginGetCountryScoreDelegate, null, this.onEndGetCountryScoreDelegate, this.onGetCountryScoreCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override OneTo50.OneTo50ServiceReference.OneTo50Soap CreateChannel() {
            return new OneTo50SoapClientChannel(this);
        }
        
        private class OneTo50SoapClientChannel : ChannelBase<OneTo50.OneTo50ServiceReference.OneTo50Soap>, OneTo50.OneTo50ServiceReference.OneTo50Soap {
            
            public OneTo50SoapClientChannel(System.ServiceModel.ClientBase<OneTo50.OneTo50ServiceReference.OneTo50Soap> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginHelloWorld(OneTo50.OneTo50ServiceReference.HelloWorldRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("HelloWorld", _args, callback, asyncState);
                return _result;
            }
            
            public OneTo50.OneTo50ServiceReference.HelloWorldResponse EndHelloWorld(System.IAsyncResult result) {
                object[] _args = new object[0];
                OneTo50.OneTo50ServiceReference.HelloWorldResponse _result = ((OneTo50.OneTo50ServiceReference.HelloWorldResponse)(base.EndInvoke("HelloWorld", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginUpdateScore(OneTo50.OneTo50ServiceReference.UpdateScoreRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("UpdateScore", _args, callback, asyncState);
                return _result;
            }
            
            public OneTo50.OneTo50ServiceReference.UpdateScoreResponse EndUpdateScore(System.IAsyncResult result) {
                object[] _args = new object[0];
                OneTo50.OneTo50ServiceReference.UpdateScoreResponse _result = ((OneTo50.OneTo50ServiceReference.UpdateScoreResponse)(base.EndInvoke("UpdateScore", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetRecordsByPage(OneTo50.OneTo50ServiceReference.GetRecordsByPageRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetRecordsByPage", _args, callback, asyncState);
                return _result;
            }
            
            public OneTo50.OneTo50ServiceReference.GetRecordsByPageResponse EndGetRecordsByPage(System.IAsyncResult result) {
                object[] _args = new object[0];
                OneTo50.OneTo50ServiceReference.GetRecordsByPageResponse _result = ((OneTo50.OneTo50ServiceReference.GetRecordsByPageResponse)(base.EndInvoke("GetRecordsByPage", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetTodayRecordsByPage(OneTo50.OneTo50ServiceReference.GetTodayRecordsByPageRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetTodayRecordsByPage", _args, callback, asyncState);
                return _result;
            }
            
            public OneTo50.OneTo50ServiceReference.GetTodayRecordsByPageResponse EndGetTodayRecordsByPage(System.IAsyncResult result) {
                object[] _args = new object[0];
                OneTo50.OneTo50ServiceReference.GetTodayRecordsByPageResponse _result = ((OneTo50.OneTo50ServiceReference.GetTodayRecordsByPageResponse)(base.EndInvoke("GetTodayRecordsByPage", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetCountryScore(OneTo50.OneTo50ServiceReference.GetCountryScoreRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetCountryScore", _args, callback, asyncState);
                return _result;
            }
            
            public OneTo50.OneTo50ServiceReference.GetCountryScoreResponse EndGetCountryScore(System.IAsyncResult result) {
                object[] _args = new object[0];
                OneTo50.OneTo50ServiceReference.GetCountryScoreResponse _result = ((OneTo50.OneTo50ServiceReference.GetCountryScoreResponse)(base.EndInvoke("GetCountryScore", _args, result)));
                return _result;
            }
        }
    }
}
